file_format: "1"
id: dactyl_manuform_4x5
name: Dactyl_manuform_4x5
type: shield
url: https://github.com/dongocduy/dactyl_4x5_zmk.git
requires: [pro_micro]
features:
  - keys
siblings:
  - dactyl_manuform_4x5_left
  - dactyl_manuform_4x5_right